USE [QLBanHang]
GO
/****** Object:  Table [dbo].[CHATLIEU]    Script Date: 4/17/2024 4:14:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHATLIEU](
	[MACHATLIEU] [int] IDENTITY(1,1) NOT NULL,
	[TENCHATLIEU] [nvarchar](50) NULL,
 CONSTRAINT [PK_tblChatLieu] PRIMARY KEY CLUSTERED 
(
	[MACHATLIEU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CHITIETHDBAN]    Script Date: 4/17/2024 4:14:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CHITIETHDBAN](
	[MAHDBAN] [int] NOT NULL,
	[MAHANG] [int] NOT NULL,
	[SOLUONG] [float] NOT NULL,
	[DONGIA] [float] NOT NULL,
	[GIAMGIA] [float] NOT NULL,
	[THANHTIEN] [float] NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_tblChiTietHDBan] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HANG]    Script Date: 4/17/2024 4:14:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HANG](
	[MAHANG] [int] IDENTITY(1,1) NOT NULL,
	[TENHANG] [nvarchar](50) NOT NULL,
	[MACHATLIEU] [int] NOT NULL,
	[SOLUONG] [float] NOT NULL,
	[DONGIANHAP] [float] NOT NULL,
	[DONGIABAN] [float] NOT NULL,
	[ANH] [nvarchar](200) NOT NULL,
	[GHICHU] [nvarchar](200) NULL,
 CONSTRAINT [PK_tblHang] PRIMARY KEY CLUSTERED 
(
	[MAHANG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HDBAN]    Script Date: 4/17/2024 4:14:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HDBAN](
	[MAHDBAN] [int] IDENTITY(1,1) NOT NULL,
	[MANHANVIEN] [int] NOT NULL,
	[NGAYBAN] [datetime] NOT NULL,
	[MAKHACH] [int] NOT NULL,
	[TONGTIEN] [float] NOT NULL,
 CONSTRAINT [PK_tblHDBan] PRIMARY KEY CLUSTERED 
(
	[MAHDBAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KHACH]    Script Date: 4/17/2024 4:14:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KHACH](
	[MAKHACH] [int] IDENTITY(1,1) NOT NULL,
	[TENKHACH] [nvarchar](50) NOT NULL,
	[DIACHI] [nvarchar](50) NOT NULL,
	[DIENTHOAI] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_tblKhach] PRIMARY KEY CLUSTERED 
(
	[MAKHACH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 4/17/2024 4:14:24 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[MANHANVIEN] [int] IDENTITY(1,1) NOT NULL,
	[TENNHANVIEN] [nvarchar](50) NOT NULL,
	[GIOITINH] [nvarchar](10) NOT NULL,
	[DIACHI] [nvarchar](50) NOT NULL,
	[DIENTHOAI] [nvarchar](15) NOT NULL,
	[NGAYSINH] [datetime] NOT NULL,
 CONSTRAINT [PK_tblNhanVien] PRIMARY KEY CLUSTERED 
(
	[MANHANVIEN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CHITIETHDBAN]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETHDBAN_HANG] FOREIGN KEY([MAHANG])
REFERENCES [dbo].[HANG] ([MAHANG])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CHITIETHDBAN] CHECK CONSTRAINT [FK_CHITIETHDBAN_HANG]
GO
ALTER TABLE [dbo].[CHITIETHDBAN]  WITH CHECK ADD  CONSTRAINT [FK_CHITIETHDBAN_HDBAN] FOREIGN KEY([MAHDBAN])
REFERENCES [dbo].[HDBAN] ([MAHDBAN])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CHITIETHDBAN] CHECK CONSTRAINT [FK_CHITIETHDBAN_HDBAN]
GO
ALTER TABLE [dbo].[HANG]  WITH CHECK ADD  CONSTRAINT [FK_HANG_CHATLIEU] FOREIGN KEY([MACHATLIEU])
REFERENCES [dbo].[CHATLIEU] ([MACHATLIEU])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HANG] CHECK CONSTRAINT [FK_HANG_CHATLIEU]
GO
ALTER TABLE [dbo].[HDBAN]  WITH CHECK ADD  CONSTRAINT [FK_HDBAN_KHACH] FOREIGN KEY([MAKHACH])
REFERENCES [dbo].[KHACH] ([MAKHACH])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HDBAN] CHECK CONSTRAINT [FK_HDBAN_KHACH]
GO
ALTER TABLE [dbo].[HDBAN]  WITH CHECK ADD  CONSTRAINT [FK_HDBAN_NHANVIEN] FOREIGN KEY([MANHANVIEN])
REFERENCES [dbo].[NHANVIEN] ([MANHANVIEN])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[HDBAN] CHECK CONSTRAINT [FK_HDBAN_NHANVIEN]
GO
